//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRDEntities : DbContext
    {
        public HRDEntities()
            : base("name=HRDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BPJS_Ms_Desa> BPJS_Ms_Desa { get; set; }
        public virtual DbSet<BPJS_Ms_Faskes> BPJS_Ms_Faskes { get; set; }
        public virtual DbSet<BPJS_Ms_Karyawan> BPJS_Ms_Karyawan { get; set; }
        public virtual DbSet<BPJS_Tr_Migrasi> BPJS_Tr_Migrasi { get; set; }
        public virtual DbSet<hrd_UserOption> hrd_UserOption { get; set; }
        public virtual DbSet<ras_AccessControlSettings> ras_AccessControlSettings { get; set; }
        public virtual DbSet<ras_AreaTime> ras_AreaTime { get; set; }
        public virtual DbSet<ras_AttLeaveRecord> ras_AttLeaveRecord { get; set; }
        public virtual DbSet<ras_AttRecord> ras_AttRecord { get; set; }
        public virtual DbSet<ras_AttResultRecord> ras_AttResultRecord { get; set; }
        public virtual DbSet<ras_AttType> ras_AttType { get; set; }
        public virtual DbSet<ras_AttTypeItem> ras_AttTypeItem { get; set; }
        public virtual DbSet<ras_Dept> ras_Dept { get; set; }
        public virtual DbSet<ras_Device> ras_Device { get; set; }
        public virtual DbSet<ras_Enroll> ras_Enroll { get; set; }
        public virtual DbSet<ras_EnrollDevice> ras_EnrollDevice { get; set; }
        public virtual DbSet<ras_GroupTime> ras_GroupTime { get; set; }
        public virtual DbSet<ras_Holiday> ras_Holiday { get; set; }
        public virtual DbSet<ras_ImageBin> ras_ImageBin { get; set; }
        public virtual DbSet<ras_Log> ras_Log { get; set; }
        public virtual DbSet<ras_LogType> ras_LogType { get; set; }
        public virtual DbSet<ras_PassTime> ras_PassTime { get; set; }
        public virtual DbSet<ras_Place> ras_Place { get; set; }
        public virtual DbSet<ras_Resources> ras_Resources { get; set; }
        public virtual DbSet<ras_RoleResources> ras_RoleResources { get; set; }
        public virtual DbSet<ras_Roles> ras_Roles { get; set; }
        public virtual DbSet<ras_Rule> ras_Rule { get; set; }
        public virtual DbSet<ras_RuleList> ras_RuleList { get; set; }
        public virtual DbSet<ras_SegmentList> ras_SegmentList { get; set; }
        public virtual DbSet<ras_Shift> ras_Shift { get; set; }
        public virtual DbSet<ras_ShiftGroup> ras_ShiftGroup { get; set; }
        public virtual DbSet<ras_ShiftList> ras_ShiftList { get; set; }
        public virtual DbSet<ras_ShiftRecord> ras_ShiftRecord { get; set; }
        public virtual DbSet<ras_ShiftSegment> ras_ShiftSegment { get; set; }
        public virtual DbSet<ras_SysSettings> ras_SysSettings { get; set; }
        public virtual DbSet<ras_UserColumns> ras_UserColumns { get; set; }
        public virtual DbSet<ras_UserDepts> ras_UserDepts { get; set; }
        public virtual DbSet<ras_UserEx> ras_UserEx { get; set; }
        public virtual DbSet<ras_UserRoles> ras_UserRoles { get; set; }
        public virtual DbSet<ras_Users> ras_Users { get; set; }
        public virtual DbSet<ras_UserSettings> ras_UserSettings { get; set; }
        public virtual DbSet<ras_Weekend> ras_Weekend { get; set; }
    }
}
