//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPJS_Ms_Faskes
    {
        public int IDX { get; set; }
        public string KODE_DIVRE { get; set; }
        public string NAMA_REGIONAL { get; set; }
        public string NAMA_KC { get; set; }
        public string NAMA_DATI2 { get; set; }
        public string KODE_FASKES { get; set; }
        public string NAMA_FASKES { get; set; }
        public string JENIS_FASKES { get; set; }
        public string ALAMAT_FASKES { get; set; }
    }
}
