//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPJS_Ms_Desa
    {
        public int IDX { get; set; }
        public string KDPROP { get; set; }
        public string NMPROP { get; set; }
        public string KDDATI2 { get; set; }
        public string NMDATI2 { get; set; }
        public string KDKEC { get; set; }
        public string NMKEC { get; set; }
        public string KDDESA { get; set; }
        public string NMDESA { get; set; }
    }
}
