//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPJS_Tr_Migrasi
    {
        public int Idx { get; set; }
        public Nullable<int> SortNo { get; set; }
        public Nullable<int> KaryawanID { get; set; }
        public string NoKK { get; set; }
        public string NoKTP { get; set; }
        public string NamaLengkap { get; set; }
        public string HubKeluarga { get; set; }
        public string TempatLahir { get; set; }
        public string TanggalLahir { get; set; }
        public string JenisKelamin { get; set; }
        public string StatusKawin { get; set; }
        public string AlamatTinggal { get; set; }
        public string RT { get; set; }
        public string RW { get; set; }
        public string KodePos { get; set; }
        public string KodeKecamatan { get; set; }
        public string NamaKecamatan { get; set; }
        public string KodeDesa { get; set; }
        public string NamaDesa { get; set; }
        public string KodeFaskesTK1 { get; set; }
        public string NamaFaskesTK1 { get; set; }
        public string KodeFaskesGigi { get; set; }
        public string NamaFaskesGigi { get; set; }
        public string Telepon { get; set; }
        public string Email { get; set; }
        public string NPP { get; set; }
        public string Jabatan { get; set; }
        public string StatusKerja { get; set; }
        public string KelasRawat { get; set; }
        public string TMTKerja { get; set; }
        public string Gaji { get; set; }
        public string WargaNegara { get; set; }
        public string NoPolis { get; set; }
        public string NamaAsuransi { get; set; }
        public string NoNPWP { get; set; }
        public string NoPassport { get; set; }
        public string NoBPJS { get; set; }
        public string AlasanMutasi { get; set; }
        public Nullable<System.DateTime> TanggalMutasi { get; set; }
        public Nullable<bool> IsDownload { get; set; }
    }
}
