//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPJS_Ms_Karyawan
    {
        public int ID { get; set; }
        public string NIP { get; set; }
        public string NamaLengkap { get; set; }
        public string Access { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Password { get; set; }
    }
}
