//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeRoleBased
    {
        public int ID { get; set; }
        public int IDV { get; set; }
        public Nullable<int> serviceYears { get; set; }
        public Nullable<int> serviceDays { get; set; }
        public int policyType { get; set; }
        public int valueType { get; set; }
        public Nullable<int> roleBasedValue { get; set; }
        public Nullable<int> currentValue { get; set; }
        public Nullable<int> balanceValue { get; set; }
        public Nullable<int> remainingValue { get; set; }
        public Nullable<System.DateTime> validDateStart { get; set; }
        public Nullable<System.DateTime> validDateStop { get; set; }
        public string decription { get; set; }
        public Nullable<int> vCreatedBy { get; set; }
        public Nullable<int> vUpdatedBy { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    
        public virtual person person { get; set; }
    }
}
