//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime dateBegin { get; set; }
        public System.DateTime dateEnd { get; set; }
        public Nullable<int> duration { get; set; }
        public int vCreatedBy { get; set; }
        public int vUpdatedBy { get; set; }
        public System.DateTime createTime { get; set; }
        public System.DateTime updateTime { get; set; }
    }
}
