//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class personEmergency
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public Nullable<int> IDVEmergencyContact { get; set; }
        public Nullable<int> relationshipType { get; set; }
        public Nullable<int> vCreatedBy { get; set; }
        public Nullable<int> vUpdatedBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
    
        public virtual person person { get; set; }
    }
}
