//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_AttRecord
    {
        public int ID { get; set; }
        public Nullable<short> DN { get; set; }
        public long DIN { get; set; }
        public System.DateTime Clock { get; set; }
        public Nullable<byte> VerifyMode { get; set; }
        public Nullable<byte> Action { get; set; }
        public string AttTypeId { get; set; }
        public System.DateTime CollectDate { get; set; }
        public Nullable<int> JobCode { get; set; }
        public Nullable<bool> Antipassback { get; set; }
        public Nullable<int> LastUpdatedUID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Remark { get; set; }
    
        public virtual ras_AttTypeItem ras_AttTypeItem { get; set; }
    }
}
