//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_AttResultRecord
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public System.DateTime AttDate { get; set; }
        public string AttId { get; set; }
        public string TimeString { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> A01 { get; set; }
        public Nullable<decimal> B01 { get; set; }
        public Nullable<decimal> B02 { get; set; }
        public Nullable<decimal> B03 { get; set; }
        public Nullable<decimal> C01 { get; set; }
        public Nullable<decimal> D01 { get; set; }
        public Nullable<decimal> D02 { get; set; }
        public Nullable<decimal> D03 { get; set; }
        public Nullable<decimal> D04 { get; set; }
        public Nullable<decimal> D05 { get; set; }
        public Nullable<decimal> D06 { get; set; }
        public Nullable<decimal> D07 { get; set; }
        public Nullable<decimal> D08 { get; set; }
        public Nullable<decimal> D09 { get; set; }
        public Nullable<decimal> D10 { get; set; }
        public Nullable<decimal> E01 { get; set; }
        public Nullable<decimal> F01 { get; set; }
        public Nullable<decimal> G01 { get; set; }
        public Nullable<decimal> G02 { get; set; }
        public Nullable<decimal> G03 { get; set; }
    
        public virtual ras_Users ras_Users { get; set; }
    }
}
