//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_Device
    {
        public int ID { get; set; }
        public short DN { get; set; }
        public Nullable<byte> Communication { get; set; }
        public Nullable<int> Baudrate { get; set; }
        public Nullable<int> ComPort { get; set; }
        public Nullable<int> Password { get; set; }
        public Nullable<int> IpPort { get; set; }
        public string IpAddress { get; set; }
        public string SN { get; set; }
        public Nullable<byte> Use { get; set; }
        public string Model { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedUID { get; set; }
        public string PlaceId { get; set; }
        public string Label { get; set; }
    
        public virtual ras_Place ras_Place { get; set; }
    }
}
