//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_Log
    {
        public int ID { get; set; }
        public string LogTypeId { get; set; }
        public System.DateTime LogDate { get; set; }
        public Nullable<int> OperateUID { get; set; }
        public string LogContent { get; set; }
        public Nullable<bool> OperateResult { get; set; }
    
        public virtual ras_LogType ras_LogType { get; set; }
    }
}
