//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_AttLeaveRecord
    {
        public int ID { get; set; }
        public int UID { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string AttTypeId { get; set; }
        public Nullable<decimal> ResultTime { get; set; }
        public Nullable<int> LastUpdatedUID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Remark { get; set; }
    
        public virtual ras_AttTypeItem ras_AttTypeItem { get; set; }
        public virtual ras_Users ras_Users { get; set; }
    }
}
