//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_UserColumns
    {
        public int UserColumnId { get; set; }
        public int UID { get; set; }
        public string ReportId { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> Width { get; set; }
        public bool Visible { get; set; }
    }
}
