//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_AttTypeItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ras_AttTypeItem()
        {
            this.ras_AttLeaveRecord = new HashSet<ras_AttLeaveRecord>();
            this.ras_AttRecord = new HashSet<ras_AttRecord>();
        }
    
        public int ID { get; set; }
        public string TypeId { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public byte Unit { get; set; }
        public bool ShowTimes { get; set; }
        public Nullable<float> MiniCalcValue { get; set; }
        public Nullable<byte> RoundType { get; set; }
        public string Symbol { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ras_AttLeaveRecord> ras_AttLeaveRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ras_AttRecord> ras_AttRecord { get; set; }
        public virtual ras_AttType ras_AttType { get; set; }
    }
}
