//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_GroupTime
    {
        public byte ID { get; set; }
        public short DN { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> PassTime0 { get; set; }
        public Nullable<int> PassTime1 { get; set; }
        public Nullable<int> PassTime2 { get; set; }
        public Nullable<int> PassTime3 { get; set; }
        public Nullable<int> PassTime4 { get; set; }
        public Nullable<int> PassTime5 { get; set; }
        public Nullable<int> PassTime6 { get; set; }
        public Nullable<int> PassTime7 { get; set; }
        public Nullable<int> PassTime8 { get; set; }
        public Nullable<int> PassTime9 { get; set; }
        public string Remark { get; set; }
    }
}
