//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_UserRoles
    {
        public int UserRoleId { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ras_Roles ras_Roles { get; set; }
        public virtual ras_Users ras_Users { get; set; }
    }
}
