//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_SegmentList
    {
        public int ID { get; set; }
        public string SegmentId { get; set; }
        public string ShiftId { get; set; }
    
        public virtual ras_Shift ras_Shift { get; set; }
        public virtual ras_ShiftSegment ras_ShiftSegment { get; set; }
    }
}
