//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_ShiftSegment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ras_ShiftSegment()
        {
            this.ras_SegmentList = new HashSet<ras_SegmentList>();
        }
    
        public int ID { get; set; }
        public string SegmentId { get; set; }
        public string SegmentName { get; set; }
        public string TypeId { get; set; }
        public string BeginAttTime { get; set; }
        public string EndAttTime { get; set; }
        public string StartWorkTime { get; set; }
        public string OffWorkTime { get; set; }
        public Nullable<bool> ToPunchIn { get; set; }
        public Nullable<bool> ToPunchOut { get; set; }
        public Nullable<bool> CalcBeLate { get; set; }
        public Nullable<bool> CalcLeaveEarly { get; set; }
        public Nullable<bool> CalcAbsence { get; set; }
        public Nullable<bool> CalcStayAway { get; set; }
        public bool CrossDays { get; set; }
        public Nullable<decimal> ResultHours { get; set; }
        public Nullable<decimal> ResultDays { get; set; }
        public Nullable<decimal> DeductMinutes { get; set; }
        public string Color { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ras_SegmentList> ras_SegmentList { get; set; }
    }
}
