//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_UserEx
    {
        public int UID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string IDNumber { get; set; }
        public string HomeAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> AttType { get; set; }
        public Nullable<int> AccessControl { get; set; }
        public Nullable<bool> ValidityPeriod { get; set; }
        public Nullable<bool> UseUserGroupACTZ { get; set; }
        public Nullable<bool> UseUserGroupVM { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> AccessTimeZone { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> InvalidDate { get; set; }
        public Nullable<int> UserGroup { get; set; }
    
        public virtual ras_Users ras_Users { get; set; }
    }
}
