//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ras_ImageBin
    {
        public string ID { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageName { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> ImageLength { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> LastUpdatedUID { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string Remark { get; set; }
    }
}
