//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeRoleBased
    {
        public int IDV { get; set; }
        public Nullable<int> catCode { get; set; }
        public Nullable<int> valueType { get; set; }
        public string value { get; set; }
        public string balance { get; set; }
    }
}
