//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class personDetail
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public string NIP { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Birthplace { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> Marital { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public Nullable<int> vCreatedBy { get; set; }
        public Nullable<int> vUpdatedBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    
        public virtual category category { get; set; }
        public virtual category category1 { get; set; }
        public virtual category category2 { get; set; }
        public virtual person person { get; set; }
    }
}
