//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleBasedMatrix
    {
        public int ID { get; set; }
        public int PolicyType { get; set; }
        public string PolicyName { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> ValueType { get; set; }
        public Nullable<int> L1 { get; set; }
        public Nullable<int> L2 { get; set; }
        public Nullable<int> L3 { get; set; }
        public Nullable<int> L4 { get; set; }
        public Nullable<int> L5 { get; set; }
        public Nullable<int> L6 { get; set; }
        public Nullable<int> L7 { get; set; }
        public Nullable<int> L8 { get; set; }
        public Nullable<int> L9 { get; set; }
        public Nullable<int> L10 { get; set; }
        public Nullable<int> L11 { get; set; }
        public Nullable<int> L12 { get; set; }
        public Nullable<int> vCreatedBy { get; set; }
        public Nullable<int> vUpdatedBy { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
