//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public class C_transactionEntities
    {
        public int txID { get; set; }
        public Nullable<int> purposeID { get; set; }
        public Nullable<int> purposeStatus { get; set; }
        public Nullable<int> idvRequest { get; set; }
        public Nullable<int> idvApproval { get; set; }
    
        public virtual C_purposeEntities C_purpose { get; set; }
    }
}
