//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;

    public class employeeEntities
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public Nullable<int> UID_ABSENCE { get; set; }
        public Nullable<System.DateTime> joinDate { get; set; }
        public Nullable<System.DateTime> resignDate { get; set; }
        public Nullable<System.DateTime> contract1Start { get; set; }
        public Nullable<System.DateTime> contract1End { get; set; }
        public Nullable<System.DateTime> contract2Start { get; set; }
        public Nullable<System.DateTime> contract2End { get; set; }
        public Nullable<System.DateTime> contract3Start { get; set; }
        public Nullable<System.DateTime> contract3End { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> vCreatedBy { get; set; }
        public Nullable<int> vUpdatedBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<int> employmentStatus { get; set; }

        public virtual personEntities personEntities { get; set; }
    }
}
