//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public  class personLanguageEntities
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public string languageName { get; set; }
        public Nullable<int> spoken { get; set; }
        public Nullable<int> written { get; set; }
        public Nullable<int> vCreatedBy { get; set; }
        public Nullable<int> vUpdatedBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }

        public virtual categoryEntities category { get; set; }
        public virtual categoryEntities category1 { get; set; }
        public virtual personEntities person { get; set; }
    }
}
