//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public class personJobEntities
    {
        public int ID { get; set; }
        public Nullable<int> IDV { get; set; }
        public Nullable<int> parentIDV { get; set; }
        public string jobName { get; set; }
        public Nullable<int> JobDivision { get; set; }
        public Nullable<int> JobDepartement { get; set; }
        public Nullable<int> JobPosition { get; set; }
        public string JobLocation { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> employmentStatus { get; set; }
        public string Note { get; set; }
        public Nullable<int> vCreatedBy { get; set; }
        public Nullable<int> vUpdatedBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }

        public virtual personEntities person { get; set; }
    }
}
